# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3], 
               [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3], 
                [4, 5, 6]], 
               
               [[7, 8, 9], 
                [10, 11, 12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [7]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [8]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 2, 3), 3, dtype('int32'), 12, numpy.ndarray)

In [13]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

a2_df = pd.DataFrame(a2)
a2_df

0  1  2
0  1  2  3
1  4  5  6

In [14]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape=(10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros(shape=(7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
# Create an array within a range of 0 and 100 with step 3
step_3_array = np.arange(0, 100, 3)
step_3_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [20]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_a1 = np.random.randint(10, size=(7, 2))
random_a1

array([[7, 0],
       [8, 0],
       [3, 2],
       [1, 8],
       [7, 2],
       [4, 4],
       [3, 7]])

In [23]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
ranmdom_a2 = np.random.random((3, 5))
ranmdom_a2

array([[0.73397533, 0.43177806, 0.06652612, 0.21261424, 0.76045994],
       [0.13056252, 0.17369366, 0.77901605, 0.57446507, 0.41459771],
       [0.85907654, 0.0380224 , 0.61539327, 0.33264699, 0.26235245]])

In [30]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_a3 = np.random.randint(10, size=(4,6))
random_a3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [34]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_a4 = np.random.randint(1, 10, size = (3, 7))

# Find the unique numbers in the array you just created
random_a4, np.unique(random_a4)

(array([[9, 7, 9, 8, 2, 1, 7],
        [7, 8, 5, 3, 8, 6, 3],
        [1, 3, 5, 3, 1, 5, 7]]),
 array([1, 2, 3, 5, 6, 7, 8, 9]))

In [37]:
# Find the 0'th index of the latest array you created
random_a4[0]

array([9, 7, 9, 8, 2, 1, 7])

In [38]:
# Get the first 2 rows of latest array you created
random_a4[:2]

array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3]])

In [45]:
# Get the first 2 values of the first 2 rows of the latest array
random_a4[:2, :2]

array([[9, 7],
       [7, 8]])

In [50]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_a5 = np.random.randint(10, size=(3, 5))
ones_a1 = np.ones(shape=(3, 5))
random_a5

array([[3, 8, 2, 6, 5],
       [7, 8, 4, 0, 2],
       [9, 7, 5, 7, 8]])

In [51]:
# Add the two arrays together
random_a5 + ones_a1

array([[ 4.,  9.,  3.,  7.,  6.],
       [ 8.,  9.,  5.,  1.,  3.],
       [10.,  8.,  6.,  8.,  9.]])

In [52]:
# Create another array of ones of shape (5, 3)

ones_a2 = np.ones(shape=(5, 3))

In [54]:
# Try add the array of ones and the other most recent array together

random_a5 + ones_a2.T

array([[ 4.,  9.,  3.,  7.,  6.],
       [ 8.,  9.,  5.,  1.,  3.],
       [10.,  8.,  6.,  8.,  9.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [55]:
# Create another array of ones of shape (3, 5)

ones_a3 = np.ones(shape=(3, 5))

In [56]:
# Subtract the new array of ones from the other most recent array
random_a5 - ones_a3

array([[ 2.,  7.,  1.,  5.,  4.],
       [ 6.,  7.,  3., -1.,  1.],
       [ 8.,  6.,  4.,  6.,  7.]])

In [57]:
# Multiply the ones array with the latest array
random_a5 * ones_a3

array([[3., 8., 2., 6., 5.],
       [7., 8., 4., 0., 2.],
       [9., 7., 5., 7., 8.]])

In [58]:
# Take the latest array to the power of 2 using '**'
random_a5 ** 2

array([[ 9, 64,  4, 36, 25],
       [49, 64, 16,  0,  4],
       [81, 49, 25, 49, 64]])

In [59]:
# Do the same thing with np.square()
np.square(random_a5)

array([[ 9, 64,  4, 36, 25],
       [49, 64, 16,  0,  4],
       [81, 49, 25, 49, 64]])

In [60]:
# Find the mean of the latest array using np.mean()
random_a5.mean()

5.4

In [61]:
# Find the maximum of the latest array using np.max()
random_a5.max()

9

In [62]:
# Find the minimum of the latest array using np.min()
random_a5.min()

0

In [63]:
# Find the standard deviation of the latest array
random_a5.std()

2.6025628394590847

In [65]:
# Find the variance of the latest array
random_a5.var()

6.7733333333333325

In [66]:
# Reshape the latest array to (3, 5, 1)
random_a5.reshape(3, 5, 1)

array([[[3],
        [8],
        [2],
        [6],
        [5]],

       [[7],
        [8],
        [4],
        [0],
        [2]],

       [[9],
        [7],
        [5],
        [7],
        [8]]])

In [67]:
# Transpose the latest array
random_a5.T

array([[3, 7, 9],
       [8, 8, 7],
       [2, 4, 5],
       [6, 0, 7],
       [5, 2, 8]])

What does the transpose do?

In [69]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1 = np.random.randint(10, size=(3, 3))
arr2 = np.random.randint(10, size=(3, 2))
arr1, arr2

(array([[1, 5, 6],
        [4, 0, 0],
        [2, 1, 4]]),
 array([[9, 5],
        [6, 3],
        [6, 7]]))

In [70]:
# Perform a dot product on the two newest arrays you created
arr1 @ arr2

array([[75, 62],
       [36, 20],
       [48, 41]])

In [71]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

arr3 = np.random.randint(10, size=(4, 3))
arr4 = np.random.randint(10, size=(4, 3))
arr3, arr4

(array([[0, 5, 7],
        [4, 3, 1],
        [5, 5, 0],
        [8, 5, 2]]),
 array([[3, 3, 2],
        [9, 2, 2],
        [3, 6, 3],
        [8, 0, 7]]))

In [75]:
# Perform a dot product on the two newest arrays you created
arr3 @ arr4.T

array([[29, 24, 51, 49],
       [23, 44, 33, 39],
       [30, 55, 45, 40],
       [43, 86, 60, 78]])

It doesn't work. How would you fix it?

In [76]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

arr3.T @ arr4

array([[115,  38,  79],
       [ 97,  51,  66],
       [ 46,  23,  30]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [79]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

arr5 = np.random.randint(10, size=(5, 6))
arr6 = np.random.randint(10, size=(5, 6))
arr5, arr6

(array([[9, 4, 6, 8, 4, 0],
        [9, 9, 0, 1, 5, 8],
        [7, 4, 0, 6, 4, 5],
        [6, 2, 9, 2, 4, 5],
        [8, 4, 0, 3, 4, 9]]),
 array([[9, 4, 6, 3, 0, 4],
        [6, 9, 9, 5, 4, 3],
        [1, 3, 9, 9, 2, 9],
        [0, 7, 4, 3, 7, 6],
        [1, 0, 3, 7, 1, 2]]))

In [80]:
# Compare the two arrays with '>'
arr5 > arr6

array([[False, False, False,  True,  True, False],
       [ True, False, False, False,  True,  True],
       [ True,  True, False, False,  True, False],
       [ True, False,  True, False, False, False],
       [ True,  True, False, False,  True,  True]])

What happens when you compare the arrays with `>`?

In [81]:
# Compare the two arrays with '>='
arr5 >= arr6

array([[ True,  True,  True,  True,  True, False],
       [ True,  True, False, False,  True,  True],
       [ True,  True, False, False,  True, False],
       [ True, False,  True, False, False, False],
       [ True,  True, False, False,  True,  True]])

In [82]:
# Find which elements of the first array are greater than 7
arr5 > 7

array([[ True, False, False,  True, False, False],
       [ True,  True, False, False, False,  True],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [ True, False, False, False, False,  True]])

In [83]:
# Which parts of each array are equal? (try using '==')
arr5 == arr6

array([[ True,  True,  True, False, False, False],
       [False,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [85]:
# Sort one of the arrays you just created in ascending order
arr5.sort()
arr5

array([[0, 4, 4, 6, 8, 9],
       [0, 1, 5, 8, 9, 9],
       [0, 4, 4, 5, 6, 7],
       [2, 2, 4, 5, 6, 9],
       [0, 3, 4, 4, 8, 9]])

In [86]:
# Sort the indexes of one of the arrays you just created
arr6.argsort()

array([[4, 3, 1, 5, 2, 0],
       [5, 4, 3, 0, 1, 2],
       [0, 4, 1, 2, 3, 5],
       [0, 3, 2, 5, 1, 4],
       [1, 0, 4, 5, 2, 3]], dtype=int64)

In [87]:
# Find the index with the maximum value in one of the arrays you've created
arr5.argmax()

5

In [88]:
# Find the index with the minimum value in one of the arrays you've created
arr5.argmin()

0

In [89]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
arr6.argmax(axis=1)

array([0, 1, 2, 1, 3], dtype=int64)

In [92]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
arr6.argmin(axis=0)

array([3, 4, 4, 0, 0, 4], dtype=int64)

In [97]:
# Create an array of normally distributed random numbers
nd_random = np.random.randn(2, 3)
nd_random

array([[ 1.55285978, -0.43951788, -0.40791535],
       [ 0.26162306,  0.01214651,  0.93093408]])

In [99]:
# Create an array with 10 evenly spaced numbers between 1 and 100
es_random = np.linspace(1, 100, num=10)
es_random

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.